### ISSUE TITLE
Evitar que o usuário precise fazer ctrl + c antes de copiar uma informação de snippet

### ISSUE THREAD

**Issue by marlon-sousa** [thgcode/snippetsForNVDA#4]
Afim de que a operação se torne mais rápida, permitir que ao pressionar ctrl + nvda + 1 até 9 o usuário seja capaz de copiar a seleção de testo e armazenar na memória ao mesmo tempo.

Para isso:

1. Obter o componente no qual o usuário está atualmente com foco. Investigar módulo api do NVDA.
2. Investigar o método makeTextInfo no objeto retornado. Note que nem todos os objetos contém texto, portanto nem sempre o tipo de objeto retornado terá acesso a este método.
3. Obter o texto selecionado.
4. Copiar a seleção para o slot de memória.

**Comment by JosielSantos** [comment]
No caso de um texto multiline, como o plugin deve se comportar?
* copiar a linha atual?
* Copiar linhas selecionadas (se houver)?
* Copiar todo o texto não importa quantas linhas tenha?

**Comment by marlon-sousa** [comment]
Para mim, deveria se comportar igual ao ctrl + c ... pegar o texto selecionado e colocar em um snippet na memória.
